# Generated by Django 3.2.3 on 2021-05-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicineName', models.CharField(max_length=200)),
                ('Introduction', models.CharField(max_length=5000)),
                ('WhenToTake', models.CharField(max_length=5000)),
                ('SideEffects', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='medicinedetect',
            name='upload',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
